describe("strudel.piano_roll", function()
  local roll
  before_each(function()
    package.loaded["strudel.piano_roll"] = nil
    roll = require("strudel.piano_roll")
    roll.setup({ max_events = 2, width = 50, height = 8 })
  end)
  after_each(function() roll.shutdown() end)

  it("normalizes JSON, modern fields, and legacy aliases", function()
    local a = roll._normalize('{"begin":2,"duration":0.5,"pitch":"C4","sound":"bd"}')
    assert.are.equal(60, a.pitch); assert.are.equal(2, a.time)
    local b = roll._normalize({ t = 3, dur = 2, s = "sd" })
    assert.are.equal("sd", b.sound); assert.is_nil(b.pitch)
  end)
  it("keeps pitch and sound-only events in separate lanes", function()
    assert.is_true(roll.handle_event({ time = 0, duration = 1, pitch = 60 }))
    assert.is_true(roll.handle_event({ time = 1, duration = 1, sound = "bd" }))
    assert.is_not_nil(roll.events[1].pitch); assert.is_nil(roll.events[2].pitch)
  end)
  it("prunes from the front", function()
    roll.handle_event({ time = 0 }); roll.handle_event({ time = 1 }); roll.handle_event({ time = 2 })
    assert.are.equal(2, #roll.events); assert.are.equal(1, roll.events[1].time)
  end)
  it("has safe lifecycle operations", function()
    roll.open(); assert.is_true(roll.is_open); roll.clear(); assert.are.equal(0, #roll.events)
    roll.close(); assert.is_false(roll.is_open); roll.open(); roll.shutdown(); assert.is_false(roll.is_open)
  end)
  it("rejects malformed input", function()
    assert.is_false(roll.handle_event("not json")); assert.is_false(roll.handle_event({ time = "nope" }))
  end)
  it("renders a float with extmarks", function()
    roll.handle_event({ time = 0, duration = 1, pitch = 60, label = "C4" })
    roll.open()
    assert.is_true(roll._valid_window()); assert.is_true(#vim.api.nvim_buf_get_extmarks(roll.bufnr, roll.ns_id, 0, -1, {}) > 0)
  end)
end)
