describe("strudel.piano_roll", function()
  local roll
  before_each(function()
    package.loaded["strudel.piano_roll"] = nil
    roll = require("strudel.piano_roll")
    roll.setup({ max_events = 2, width = 50, height = 8 })
  end)
  after_each(function() roll.shutdown() end)

  it("normalizes JSON, modern fields, and legacy aliases", function()
    local a = roll._normalize('{"begin":2,"duration":0.5,"pitch":"C4","sound":"bd"}')
    assert.are.equal(60, a.pitch); assert.are.equal(2, a.time)
    local b = roll._normalize({ t = 3, dur = 2, s = "sd" })
    assert.are.equal("sd", b.sound); assert.is_nil(b.pitch)
  end)
  it("keeps pitch and sound-only events in separate lanes", function()
    assert.is_true(roll.handle_event({ time = 0, duration = 1, pitch = 60 }))
    assert.is_true(roll.handle_event({ time = 1, duration = 1, sound = "bd" }))
    assert.is_not_nil(roll.events[1].pitch); assert.is_nil(roll.events[2].pitch)
  end)
  it("prunes from the front", function()
    roll.handle_event({ time = 0 }); roll.handle_event({ time = 1 }); roll.handle_event({ time = 2 })
    assert.are.equal(2, #roll.events); assert.are.equal(1, roll.events[1].time)
  end)
  it("has safe lifecycle operations", function()
    roll.open(); assert.is_true(roll.is_open); roll.clear(); assert.are.equal(0, #roll.events)
    roll.close(); assert.is_false(roll.is_open); roll.open(); roll.shutdown(); assert.is_false(roll.is_open)
  end)
  it("rejects malformed input", function()
    assert.is_false(roll.handle_event("not json")); assert.is_false(roll.handle_event({ time = "nope" }))
  end)
  it("renders a float with extmarks", function()
    roll.handle_event({ time = 0, duration = 1, pitch = 60, label = "C4" })
    roll.open()
    assert.is_true(roll._valid_window()); assert.is_true(#vim.api.nvim_buf_get_extmarks(roll.bufnr, roll.ns_id, 0, -1, {}) > 0)
  end)

  it("renders inline without changing source text", function()
    local bufnr = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { 'note("c4")', "second line" })
    local before = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
    roll.handle_event({ time = 0, duration = 1, pitch = 60 })
    roll.set_inline_target(bufnr, 0)
    assert.are.same(before, vim.api.nvim_buf_get_lines(bufnr, 0, -1, false))
    local marks = vim.api.nvim_buf_get_extmarks(bufnr, roll.inline_ns_id, 0, -1, { details = true })
    assert.are.equal(1, #marks)
    assert.is_not_nil(marks[1][4].virt_lines)
    assert.is_false(marks[1][4].virt_lines_above)
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end)

  it("uses arrival time and note sound fallback for legacy events", function()
    roll._arrival_origin = nil
    local first = roll._normalize({ s = "note:C4", dur = 0.25 }, 10)
    local second = roll._normalize({ s = "bd", dur = 0.5 }, 11)
    assert.are.equal(0, first.time); assert.are.equal(60, first.pitch)
    assert.are.equal(0.25, first.duration); assert.are.equal(1, second.time)
    assert.is_nil(second.pitch)
  end)

  it("supports multiple inline targets and clears one buffer safely", function()
    local first = vim.api.nvim_create_buf(false, true)
    local second = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(first, 0, -1, false, { "one", "two" })
    vim.api.nvim_buf_set_lines(second, 0, -1, false, { "three" })
    roll.set_inline_target(first, 0)
    roll.set_inline_target(first, 4)
    roll.set_inline_target(second, 0)
    assert.are.equal(2, #vim.api.nvim_buf_get_extmarks(first, roll.inline_ns_id, 0, -1, {}))
    assert.are.equal(1, #vim.api.nvim_buf_get_extmarks(second, roll.inline_ns_id, 0, -1, {}))
    roll.clear_inline(first)
    assert.are.equal(0, #vim.api.nvim_buf_get_extmarks(first, roll.inline_ns_id, 0, -1, {}))
    vim.api.nvim_buf_delete(first, { force = true })
    vim.api.nvim_buf_delete(second, { force = true })
    roll._redraw_inline()
    assert.is_nil(roll.inline_targets[first])
  end)

  it("scopes inline target cleanup by absolute source byte offset", function()
    local bufnr = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { "first target", "second target" })
    roll.set_inline_target(bufnr, 0)
    roll.set_inline_target(bufnr, 20)
    roll.clear_inline_targets(bufnr, 0, 12)
    assert.are.equal(1, #roll.inline_targets[bufnr])
    assert.are.equal(20, roll.inline_targets[bufnr][1].byte_offset)
    assert.are.equal(1, #vim.api.nvim_buf_get_extmarks(bufnr, roll.inline_ns_id, 0, -1, {}))
    roll.clear_inline_targets(bufnr, 20, 20)
    assert.is_nil(roll.inline_targets[bufnr])
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end)
end)
